### ISSUE TITLE
Inkplate File is too large

### ISSUE THREAD

**Issue by markus-seidl** [e-radionicacom/Inkplate-micropython#18]
I've tried to upload the inkplate6plus file to the device but got errors while uploading. The smaller files (like the mcp one) uploaded flawlessly. 
So my guess is it's too large. Additionally, from a clean code standpoint, a file with over a 1000 line is hard to understand.

**Comment by kratz00** [comment]
@markus-seidl Please add more details:

- what MicroPython version are you running
- what command did you use to upload files
- what is the error message you get

**Comment by markus-seidl** [comment]
Sorry, but I abandoned the project completely and moved to a different product.

**Comment by tritip** [comment]
What product please?— cOn Dec 20, 2022, at 07:53, Markus Seidl ***@***.***> wrote:﻿
Sorry, but I abandoned the project completely and moved to a different product.

**Comment by markus-seidl** [comment]
I was totally unsatisfied with this python implementation, so I've moved one up to a kindle tablet (which is equally expensive) and used this as a simple wall mounted display. It has a lot of different caveats for my use case, but it was tremendously simpler to program.
