### ISSUE TITLE
GFX does not respect rotation

### ISSUE THREAD

**Issue by ebrynne** [e-radionicacom/Inkplate-micropython#25]
GFX is initialized with `D_COLS` and `D_ROWS` as its `width` and `height` respectively. But because those are not affected by rotation, any logic regarding the x/y coordinates of later draw operations are checked against the default orientation regardless of configured rotation. 

Draw functions fail silently if asked to draw out of bounds, so because of this bug nothing can be drawn in portrait orientation beyond the 758th pixel. 

As an example:

``` 
from inkplate6_PLUS import Inkplate

display = Inkplate(Inkplate.INKPLATE_1BIT)

if __name__ == "__main__":
    display.begin()
    display.setRotation(1)
    display.drawRect(300, 100, 100, 100, display.BLACK)
    display.drawRect(300, 500, 100, 100, display.BLACK)
    display.drawRect(300, 900, 100, 100, display.BLACK)
    display.display()
```

Expected: Three squares
Result: Two squares

The third square is rejected by the check:
```
if y0 < -height or y0 > self.height or x0 < -width or x0 > self.width:
            return
```

For anyone running into the same problem, a quick fix is initializing your display and then just swapping the width/height. It hasn't broken anything for me... yet. 
```
self.display = Inkplate(Inkplate.INKPLATE_1BIT)
self.display.begin()
self.display.setRotation(1)
# GFX draw functions do nothing if drawn outside known range, and don't respect rotation. 
self.display.GFX.height = 1024
self.display.GFX.width = 758
```

**Comment by rsoric** [comment]
Hi @ebrynne 

We have had a look at this and tested it - it seems to work great. We really appreciate you taking the time to offer your suggestion for the solution. 

We're always looking to increase our support for MicroPython, so after some more refactoring and testing - we'll make sure to include this in an official release of the repository sometime soon. We'll notify you here when the working code for this is up on the dev branch of this repo.

**Comment by rsoric** [comment]
hi @ebrynne 

This was fixed in the [latest update](https://github.com/SolderedElectronics/Inkplate-micropython/commit/103e107195186d86ce219b335b4c51a1d0b9105f) to the Inkplate Micropython library. Thanks again!
