### ISSUE TITLE
Frontlight support to the soldered_inkplate6_PLUS

### ISSUE THREAD

**Issue by svanya** [e-radionicacom/Inkplate-micropython#27]
Please add frontlight support to the soldered_inkplate6_PLUS.

**Comment by rsoric** [comment]
Hi @svanya , just made a push to the dev branch which has this feature for Soldered Inkplate6PLUS, give it a try in the frontlight.py example. It's working for me.

Please download it from the dev branch for now, it will be released on the main branch soon, when we get a chance to test out some more features.

-Rob

**Comment by svanya** [comment]
Hi, @rsoric, it's working great. Thanks a lot👍

**Comment by rsoric** [comment]
@svanya glad to hear! Closing this issue.
