### ISSUE TITLE
Can not preserve RTC time across reboots (Inkplate 5)

### ISSUE THREAD

**Issue by Danielside** [e-radionicacom/Inkplate-micropython#31]
Dear team:

As pointed out by Robert Sorić in response to an email, it seems that currently the micropython library is using the internal ESP32 RTC but not the external one. I am interested in using the external one in order to preserve date and time across reboots by using a cr2032 battery.

Anyway, here is the original communication:

* I have installed a brand new cr2032 battery (yes, with correct polarity)
* I copy this simple main.py to root https://git.sr.ht/~danielside/PruebasInkplate/tree/master/item/main.py
* I have a script that sets date and time, and afterwards it prints them out
https://git.sr.ht/~danielside/PruebasInkplate/tree/master/item/setdatetime.py.
I have tried with both init and setdatetime with the same result.
* I know that the rtc is working because if I execute this script several
minutes later it prints the correct time
https://git.sr.ht/~danielside/PruebasInkplate/tree/master/item/printdatetime.py
With the date and time correctly set, with the rtc ticking, and main.py copied,
and the battery installed.... I reboot (I/O button next to usb-c) and the time
is lost, main.py prints 0:0

Regards,
Daniel.

**Comment by rsoric** [comment]
Hi @Danielside ,

thanks for submitting this, the feature request is totally valid. I'll comment an update on this likely during next week. 

-Rob

**Comment by rsoric** [comment]
Hi @Danielside , just writing here with a quick update, unfortunately I'll have to push back writing this until next week due to some other deadlines.

**Comment by Danielside** [comment]
Hi @rsoric, any progress on this issue?

**Comment by rsoric** [comment]
Hi @Danielside ,

sorry for the delayed response, we were working on some other projects. 

I'll actually have some time to put aside for this later today and tomorrow, so, expect a response.

**Comment by rsoric** [comment]
Hi @Danielside , I've implemented some basic functionality for this for Inkplate5 only, for now. It's on the dev branch:
https://github.com/SolderedElectronics/Inkplate-micropython/commit/5477f3099279492ddcce63ddde2b272ebea8ef4f

There is a RTC example in the examples folder. Give it a try, it's working fine on my device.

Won't close this issue yet because it should really get implemented for all Inkplates.

Thanks for being patient with us regarding this feature.

-Rob

**Comment by Danielside** [comment]
It works great, thank you! I have been able to set time and date, power off the device, powering on again and see that the time has been preserved.

Daniel

**Comment by rsoric** [comment]
Glad to hear it works! 

I'd like just to keep this issue open until we implement it for all Inkplates, to make tracking this easier.

**Comment by rsoric** [comment]
Added this to the latest push to main: https://github.com/SolderedElectronics/Inkplate-micropython/commit/05651f6ee36eb016f358dae178d5f022e75ebc0a

Considering this officially closed.
