### ISSUE TITLE
Can't read touch sensor of Inkplate6COLOR

### ISSUE THREAD

**Issue by besi** [e-radionicacom/Inkplate-micropython#34]
Hello I am trying out the examples of this repository. 

I did upload the following files into a lib folder:
<img width="217" alt="Screenshot 2024-01-23 at 00 28 54" src="https://github.com/SolderedElectronics/Inkplate-micropython/assets/160412/f15b123c-5639-4416-8247-04ac27259e47">

Now when I want to run the touchpads.py file I will get an error at the following line:
https://github.com/SolderedElectronics/Inkplate-micropython/blob/master/Examples/Inkplate6COLOR/touchpads.py#L38

     File "<stdin>", line 38, in <module>
     AttributeError: 'Inkplate' object has no attribute 'TOUCH1'

**Comment by rsoric** [comment]
Hi @besi 

sorry for the late rersponse, we're not prioritizing MicroPython support at this time, there were very few Inkplate 6COLOR boards with the touchpads, so this was not implemented. If you want to implement it yourself, check how the touch sensors are implemented for Inkplate 10 in Inkplate10.py. Use that as a base, but re-work them to work with the PCAL expander, the one which is already in use for Inkplate 6COLOR.
