### ISSUE TITLE
Image to Bytemap converter

### ISSUE THREAD

**Issue by misel228** [e-radionicacom/Inkplate-micropython#37]
As far as I can see that Inkplate2 can't load PNG files.

Do you have a tool at hand that converts a BMP and/or PNG file to a byte map like this one:

https://github.com/SolderedElectronics/Inkplate-micropython/blob/05651f6ee36eb016f358dae178d5f022e75ebc0a/color_image_inkplate2.py

It's not very complicated to create one but I figured, you might have already done so. :)

**Comment by rsoric** [comment]
Hi @misel228 

we have indeed worked on a tool like this but it's not finished yet. For now, for micropython, you can do this: use this image converter: https://solderedelectronics.github.io/Inkplate-image-converter/

Convert for Inkplate2 and then just change the format from c++ to micropython. This should work and was the basic idea for the image converter.

-Rob
